service: usampl

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: eu-west-2
  profile: default
  apiKeys:
    - usamplkey

functions:
  sendemail:
    handler: handler.sendemail
    events:
      - http:
          path: sendemail
          method: post
          private: true
          cors: true
